[communication]


[model]

#module = 'static/Model/SonoNet_PyTorch-master/test'
#function = "runIt"

module = 'static/Model/COVID_19_detection_with_Chest_X_Ray_using_PyTorch_master/evaluation_metrics'
function = "main"


[image_capture]


image_capture_button = false

image_capture_freeze = true

image_capture_background = true

device_name = "DVI2USB 3.0 D2S342374"

resolution = [640,480]

fps = 4

[interface]
#the interface is split in 4 different squares 2 rows an 2 columns
#The format is a follows
#[1][2]
#[3][4]
#pick where you want to place the different elements
#If there are anything not needed or not gonna be visualized set value to 0
  [interface.button]
  button_placement = 3
  [interface.images]
  captured_image_placement = 1
  analyzed_image_placement = 2
  [interface.results]
  result_list_placement = 2
  description_placement = 2
  [interface.standardplanes]
  standardplanes_placement = 0




[returns]
  [returns.output]
  #specify the model output indecies order for different results
  image_index = 0

  labels_index = 1

  result_index = 2

  description_index = 3

  [returns.image]

  image_bool = true

  image_format = '.png'

  [returns.description]

  description_bool = true

  [returns.results]

  result_bool =true

  [returns.labels]

  labels_bool = true
